### PR TITLE
update dependencies to latest stable version

### PR DESCRIPTION
**Pull request by hengkiardo**
hi @mcollina please checking. Thanks

### CODE REVIEW

**Comment by mcollina** [comment]
Why? The current semver range already include those, or am I missing something?

**Comment by hengkiardo** [comment]
@mcollina i think so, 
because now in npm, dependencies still use the old version
```
"fastfall": "^1.5.0",
"fastparallel": "^2.2.0",
"fastq": "^1.3.0",
"fastseries": "^1.7.0",
"reusify": "^1.0.0"
```
so on this PR, the dependencies using the latest and stable version

**Comment by mcollina** [comment]
@aredo I think something else is going on in your machine if your are downloading old versions. If you `npm i steed`, you will get the latest versions of the dependencies.

**Comment by hengkiardo** [comment]
@mcollina yes maybe.

but I just checking dependencies [fastq](https://www.npmjs.com/package/fastq) now its `1.5.0` but in `package.json` its still `1.3.0`

**Pull request closed without merging**
